version: '3'
services:
  service:
    build: .
    volumes:
      - ./server:/usr/src/app/server
      - ./client:/usr/src/app/client
      - ./server/fixtures:/data/masters
      - ./server/tmp:/data/cache
    command: yarn start
    ports:
      - 80:80
