version: '3.9'
services:
  client:
    image: pirelenito/node-ffmpeg-imagemagick:latest
    working_dir: /usr/src/app/client
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    command: yarn start

  server:
    image: pirelenito/node-ffmpeg-imagemagick:latest
    working_dir: /usr/src/app/server
    volumes:
      - ./:/usr/src/app
      - ./server/fixtures:/data/masters
      - ./server/tmp:/data/cache
    ports:
      - 8080:80
    command: yarn watch
